apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jtcressy-net-235001
  name: mysql-primary-instance
  namespace: default
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    activationPolicy: ALWAYS
    availabilityType: ZONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      enabled: true
      startTime: "08:00"
      transactionLogRetentionDays: 7
    diskAutoresize: true
    diskSize: 10
    diskType: PD_SSD
    ipConfiguration:
      privateNetworkRef:
        external: projects/jtcressy-net-235001/global/networks/default
    locationPreference:
      zone: us-central1-a
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
    tier: db-f1-micro