apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: home-k8s
  namespace: default
spec:
  controlPlaneEndpoint:
    host: home-k8s-apiserver
    port: 6443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: NestedControlPlane
    name: home-k8s-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
    kind: NestedCluster
    name: home-k8s
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: NestedCluster
metadata:
  name: home-k8s
  namespace: default
spec:
  controlPlaneEndpoint:
    host: localhost
    port: 6443
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: NestedControlPlane
metadata:
  name: home-k8s-control-plane
  namespace: default
spec:
  apiserver:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: NestedAPIServer
    name: home-k8s-nestedapiserver
  controllerManager:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: NestedControllerManager
    name: home-k8s-nestedcontrollermanager
  etcd:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
    kind: NestedEtcd
    name: home-k8s-nestedetcd
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: NestedEtcd
metadata:
  name: home-k8s-nestedetcd
  namespace: default
spec:
  replicas: 1
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: NestedAPIServer
metadata:
  name: home-k8s-nestedapiserver
  namespace: default
spec:
  replicas: 1
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha4
kind: NestedControllerManager
metadata:
  name: home-k8s-nestedcontrollermanager
  namespace: default
spec:
  replicas: 1