apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
rules:
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["tailscale"]
  resources: ["secrets"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
- kind: ServiceAccount
  name: tailscale
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-k8s-tailscale-proxy
template:
  spec:
    serviceAccountName: tailscale
    initContainers:
    - name: sysctler
      image: busybox
      securityContext:
        privileged: true
      command: ["/bin/sh"]
      args:
        - -c
        - sysctl -w net.ipv4.ip_forward=1
      resources:
        requests:
          cpu: 1m
          memory: 1Mi
    containers:
    - name: tailscale
      imagePullPolicy: Always
      image: ghcr.io/tailscale/tailscale:v1.18.2
      env: 
      # Store the state in a k8s secret
      - name: HOSTNAME
        value: "home-k8s-apiserver"
      - name: KUBE_SECRET
        value: "tailscale"
      - name: USERSPACE
        value: "false"
      - name: AUTH_KEY
        valueFrom:
          secretKeyRef:
            name: tailscale-auth
            key: AUTH_KEY
            optional: true
      - name: DEST_IP
        value: "home-k8s-apiserver"

      securityContext:
        capabilities:
          add:
          - NET_ADMIN