---
apiVersion: v1
kind: Service
metadata:
  name: k3s-server
  labels:
    app.kubernetes.io/component: k3s-server-server
spec:
  selector:
    app.kubernetes.io/name: k3s-server
    app.kubernetes.io/component: k3s-server-server
  type: ClusterIP
  ports:
  - name: api
    port: 6443
    targetPort: 6443
---
apiVersion: v1
kind: Service
metadata:
  name: k3s-server-headless
  labels:
    app.kubernetes.io/component: k3s-server-server
spec:
  selector:
    app.kubernetes.io/component: k3s-server-server
  type: ClusterIP
  clusterIP: None
  ports:
  - name: api
    port: 6443
    targetPort: 6443