apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/1password
  - ../base/cert-manager
  - ../base/gateway-api
  - ../base/sources
  - traefik
  - ../base/csi-secrets-store
  # - ../base/cloudsql
  - ../base/cluster-api
transformers:
  - global-labels.yaml