apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: vault-gcs
  namespace: vault
  annotations:
    cnrm.cloud.google.com/project-id: jtcressy-net-235001
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: vault-jtcressy-net
    namespace: vault
  bindings:
    - role: roles/storage.admin
      members:
        - serviceAccount:vault-server@jtcressy-net-235001.iam.gserviceaccount.com
    - role: roles/storage.objectAdmin
      members:
        - serviceAccount:vault-server@jtcressy-net-235001.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: vault-kms
  namespace: vault
  annotations:
    cnrm.cloud.google.com/project-id: jtcressy-net-235001
spec:
  resourceRef:
    apiVersion: kms.cnrm.cloud.google.com/v1beta1
    kind: KMSCryptoKey
    name: vault-key
    namespace: vault
  bindings:
    - role: roles/cloudkms.cryptoKeyEncrypterDecrypter
      members:
        - serviceAccount:vault-server@jtcressy-net-235001.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: sa-wi-policy-vault
  namespace: vault
  annotations:
    cnrm.cloud.google.com/project-id: jtcressy-net-235001
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: vault-server
    namespace: vault
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:jtcressy-net-235001.svc.id.goog[vault/vault-ksa]
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: vault-gcp-auth
  namespace: vault
  annotations:
    cnrm.cloud.google.com/project-id: jtcressy-net-235001
spec:
  bindings:
    - role: roles/iam.serviceAccountKeyAdmin
      members:
        - serviceAccount:vault-server@jtcressy-net-235001.iam.gserviceaccount.com