apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  releaseName: rancher
  chart:
    spec:
      chart: rancher
      version: "2.6.2"
      sourceRef:
        kind: HelmRepository
        name: rancher-latest
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    hostname: rancher.jtcressy.net
    privateCA: true
    tls: external
    ingress:
      extraAnnotations:
        traefik.ingress.kubernetes.io/preserve-host: "true"
        ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
      tls:
        source: secret
        secretName: tls-rancher-ingress