apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: gateway-api
spec:
  interval: 30m
  path: "./config/crd"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
  