apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-v2
spec:
  values:
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
    service:
      annotations: {}