apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.4/manifests/ha/install.yaml
configMapGenerator:
- name: argocd-cm
  namespace: argocd
  behavior: merge
  files:
  - configs/...
