apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-v2
resources:
  - namespace.yaml
  - cf-tunnel-secret.yaml
  - cf-tunnel-config.yaml
  - cf-origin-crt-secret.yaml
  - traefik-pilot-secret.yaml
  - traefik-config.yaml
  - release.yaml
  - dashboard-route.yaml