version: "3.4"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        VARIANT: focal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tailscale-socket:/var/run/tailscale
    depends_on:
      - "tailscale"
    networks: devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done"
  tailscale:
    image: docker.io/jauderho/tailscale:v1.14.0
    env_file: /root/.codespaces/shared/.env
    networks: devcontainer
    entrypoint:
      - /bin/sh
      - -c
      - export TAILSCALE_AUTH=$TAILSCALE_EPHEMERAL_AUTHKEY && sh /entrypoint.sh
    environment: 
      HOSTNAME: codespaces
      TAILSCALE_AUTH: "$TAILSCALE_EPHEMERAL_AUTHKEY"
    volumes:
      - /var/lib/docker/codespacemount/.persistedshare/tailscale:/tailscale
      - tailscale-socket:/var/run/tailscale
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - CAP_SYS_RAWIO
    restart: unless-stopped

volumes:
  tailscale-socket:

networks:
  devcontainer:
    driver: overlay