# Example command to install and configure k3s to join the below cluster over tailscale
# The K3S_URL should match the hostname of the tailscale proxy deployment
#   which is determined by the format https://$(CLUSTER_NAME)-k3s-server:6443
# Optionally, you may append your tailnet FQDN to ensure dns discovery in case search domains are improperly configured.
##
## curl -sfL http://get.k3s.io | K3S_URL=https://edge-k3s-server:6443 K3S_TOKEN="[REDACTED]" sh -s - --flannel-iface tailscale0
##
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k3s-cluster-edge
commonLabels:
  app.kubernetes.io/instance: edge
transformers:
- global-labels.yaml
resources:
- ../../base
- onepass-k3s-token.yaml
- apiserver-ingress.yaml
# - apiserver-ingress.yaml
images:
- name: rancher/k3s
  newTag: v1.21.10-k3s1
- name: ghcr.io/tailscale/tailscale
  newTag: v1.22.1
replicas:
- name: k3s-server
  count: 3
- name: tailscale-proxy
  count: 1
configMapGenerator:
- name: cluster-facts
  namespace: k3s-cluster
  behavior: merge
  literals:
  - CLUSTER_NAME=edge
patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      name: k3s-server
      namespace: k3s-cluster
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: https
        traefik.ingress.kubernetes.io/service.serverstransport: k3s-cluster-edge-k3s-server@kubernetescrd