apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: k3s-cluster-secrets
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/jtcressy-net-infra/items/k3s-cluster-edge