apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: origin-ca-issuer
  namespace: origin-ca-issuer
spec:
  interval: 5m
  path: "./deploy/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-origin-ca-issuer
    namespace: flux-system
  timeout: 2m