apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onepassword
resources:
  - namespace.yaml
  - crds/onepassword.com_onepassworditems_crd.yaml
  - connect
  - rbac.yaml
  - operator.yaml
# Manually create two secrets after applying the above:
# cat 1password-credentials.json | base64 | tr '/+' '_-' | tr -d '=' | tr -d '\n' > op-session
# kubectl -n onepassword create secret generic op-credentials --from-file=op-session=op-session
# kubectl -n onepassword create secret generic onepassword-token --from-literal=token=<OP_CONNECT_TOKEN>