# Example command to install and configure k3s to join the below cluster over tailscale
# The K3S_URL should match the hostname of the tailscale proxy deployment
#   which is determined by the format https://$(CLUSTER_NAME)-k3s-server:6443
# Optionally, you may append your tailnet FQDN to ensure dns discovery in case search domains are improperly configured.
##
## curl -sfL http://get.k3s.io | K3S_URL=https://home-udm-k8s-k3s-server:6443 K3S_TOKEN="[REDACTED]" sh -s - --flannel-iface tailscale0
##
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k3s-servers-home-udm-k8s
commonLabels:
  app.kubernetes.io/instance: home-udm-k8s
transformers:
- global-labels.yaml
resources:
- ../../base
- onepass-k3s-token.yaml
# - apiserver-ingress.yaml
images:
- name: rancher/k3s
  newTag: v1.21.9-k3s1
- name: ghcr.io/tailscale/tailscale
  newTag: v1.20.4
replicas:
- name: k3s-server
  count: 3
- name: tailscale-proxy
  count: 1
configMapGenerator:
- name: cluster-facts
  namespace: k3s-servers
  behavior: merge
  literals:
  - CLUSTER_NAME=home-udm-k8s
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: tailscale-proxy
    annotations:
      operator.1password.io/item-path: "vaults/jtcressy-net-infra/items/k3s-server-home-udm-k8s-tailscale-key"
      operator.1password.io/item-name: "tailscale-auth"
  spec:
    template:
      spec:
        containers:
        - name: tailscale
          env:
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                optional: false
  