apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    gcs.csi.ofek.dev/bucket: bw-jtcressy-net
    gcs.csi.ofek.dev/gid: "2000"
    gcs.csi.ofek.dev/uid: "1000"
    volume.beta.kubernetes.io/storage-provisioner: gcs.csi.ofek.dev
  name: bitwarden-bucket
  namespace: bitwarden
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-gcs
  volumeMode: Filesystem