apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitwarden
  name: bitwarden
  namespace: bitwarden
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: websocket
    port: 3012
    protocol: TCP
    targetPort: 3012
  selector:
    app: bitwarden
  sessionAffinity: None
  type: ClusterIP