apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: OVERRIDE_ME
      protocol: layer2
      addresses:
      - 192.168.1.240-192.168.1.250
