name: Network Testing

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/network-testing.yml'

env:
  VAULT_ADDR: https://vault.jtcressy.net/

jobs:
  network-testing:
    runs-on: ubuntu-latest
    services:
      op-connect-sync:
        image: 1password/connect-api:latest
        ports:
          - 8080:8080
        volumes:
          - op-data:/home/opuser/.op/data
        env:
          OP_SESSION: ${{ secrets.OP_CREDENTIALS_B64 }}
      op-connect-api:
        image: 1password/connect-sync:latest
        ports:
          - 8081:8080
        volumes:
          - op-data:/home/opuser/.op/data
        env:
          OP_SESSION: ${{ secrets.OP_CREDENTIALS_B64 }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure 1Password Connect
      uses: 1password/load-secrets-action/configure@v1
      with:
        connect-host: http://localhost:8080
        connect-token: ${{ secrets.OP_ACCESS_TOKEN }}
    
    - name: Load Secrets
      uses: 1password/load-secrets-action@v1
      env:
        TAILSCALE_AUTHKEY: op://jtcressy-net-infra/tailscale/ephemeral/credential

    - name: Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ env.TAILSCALE_AUTHKEY }}

    - name: Network Info Commands
      run: |
        ip route show table all && \
        ip addr show

    - name: IPV6 Checks
      run: |
        [ -f /proc/net/if_inet6 ] && echo 'IPv6 ready system!' || echo 'No IPv6 support found! Compile the kernel!!' && \
        ip -6 route show table all && \
        curl -6 -vvv https://ipv6.google.com || true && \
        ping -6 ipv6.google.com -c 4 || true

    - name: Test connection to remote subnet (192.168.20.1/24)
      run: |
        ping 192.168.20.1 -c 4 || true

    - name: check connection to home gateway
      run: |
        tailscale ping gw || true && \
        ping $(tailscale ip --4 gw) -c 4 || true && \
        ping6 $(tailscale ip --6 gw) -c 4 || true && \
        curl -svk -m 5 https://gw.jtcressy.net.beta.tailscale.net || true && \
        curl -6svk -m 5 https://gw.jtcressy.net.beta.tailscale.net || true

