name: Build Raspberry Pi Discovery Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'pi-discovery/**'
    - '.github/workflows/pi-discovery-image.yml'

env:
  VAULT_ADDR: https://vault.jtcressy.net/

jobs:
  configure-and-publish-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu-release:
        - "focal"
        - "impish"
    services:
      op-connect-sync:
        image: 1password/connect-api:latest
        ports:
          - 8080:8080
        volumes:
          - op-data:/home/opuser/.op/data
        env:
          OP_SESSION: ${{ secrets.OP_CREDENTIALS_B64 }}
      op-connect-api:
        image: 1password/connect-sync:latest
        ports:
          - 8081:8080
        volumes:
          - op-data:/home/opuser/.op/data
        env:
          OP_SESSION: ${{ secrets.OP_CREDENTIALS_B64 }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure 1Password Connect
      uses: 1password/load-secrets-action/configure@v1
      with:
        connect-host: http://localhost:8080
        connect-token: ${{ secrets.OP_ACCESS_TOKEN }}
    
    - name: Load Secrets
      uses: 1password/load-secrets-action@v1
      env:
        TAILSCALE_EPHEMERAL_AUTHKEY: op://jtcressy-net-infra/tailscale/ephemeral/credential
        TAILSCALE_REUSABLE_AUTHKEY: op://jtcressy-net-infra/tailscale/reusable/credential
        K3S_TOKEN: op://jtcressy-net-infra/k3s-server-home-udm-k8s-token

    - name: Tailscale
      uses: tailscale/github-action@effa99fe9dc68518c77d0e7c00879f6599714d39
      with:
        authkey: ${{ env.TAILSCALE_EPHEMERAL_AUTHKEY }}
        args: "--advertise-tags=tag:ghactions"

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - run: echo "IMAGE_FILE_PATH=$(curl --silent http://cdimage.ubuntu.com/releases/streams/v1/com.ubuntu.cdimage:ubuntu.json | jq -r '.products[] | select(.image_type == "preinstalled-server" and .arch == "arm64+raspi" and .release == "${{ matrix.ubuntu-release }}") | .versions[].items."img.xz".path')" >> $GITHUB_ENV
    - run: echo "IMAGE_DOWNLOAD_URL=https://cdimage.ubuntu.com/$IMAGE_FILE_PATH" >> $GITHUB_ENV

    - name: Download Ubuntu ${{ matrix.ubuntu-version }} Image
      run: curl -LJO $IMAGE_DOWNLOAD_URL

    - name: Decompress Image
      run: |
        xz -dv ubuntu-*.img.xz
        
    - run: echo "IMAGE_FILE_NAME=$(ls ubuntu-*.img)" >> $GITHUB_ENV
    - run: echo "LOOP_DEVICE=$(sudo losetup --find --partscan --show $IMAGE_FILE_NAME)" >> $GITHUB_ENV

    - name: Mount Image
      run: |
        sudo mkdir -p /mnt/ubuntu-boot
        sudo mkdir -p /mnt/ubuntu-root
        sudo mount -o loop "${LOOP_DEVICE}p1" /mnt/ubuntu-boot
        sudo mount -o loop "${LOOP_DEVICE}p2" /mnt/ubuntu-root

    - name: Customize Image
      run: |
        sudo cp -R pi-discovery/boot/* /mnt/ubuntu-boot/
        echo ${TAILSCALE_REUSABLE_AUTHKEY} > tailscale-authkey
        sudo mv tailscale-authkey /mnt/ubuntu-boot/tailscale-authkey
        echo "$K3S_TOKEN" > /mnt/ubuntu-boot/k3s_token
        echo "https://home-udm-k8s-k3s-server:6443" > /mnt/ubuntu-boot/k3s_url

    - name: Unmount Image
      run: |
        sync
        sudo umount /mnt/ubuntu-boot
        sudo umount /mnt/ubuntu-root
        sudo losetup --detach ${LOOP_DEVICE}

    - name: Re-Compress Image
      run: xz -vT0 ubuntu-*.img

    - run: echo "IMAGE_FILE_NAME_COMPRESSED=$(ls ubuntu-*.img.xz)" >> $GITHUB_ENV

    - name: Upload to secure Google Cloud Storage bucket
      id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: '${{ env.IMAGE_FILE_NAME_COMPRESSED }}'
        destination: 'jtcressy-rpi-images/'